; ============================================================
; Tamagotchi Argentino — PlatformIO config
; Hardware: ESP32-C6 + LCD IPS 1.47" (ST7789, 172x320)
; Librería gráfica: Arduino_GFX (igual que el proyecto JARVIS)
; ============================================================
[env:esp32-c6-devkitc-1]
platform  = espressif32
board     = esp32-c6-devkitc-1
framework = arduino

monitor_speed = 115200

lib_deps =
    moononournation/Arduino_GFX_Library @ ^1.4.9

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DPANTALLA_ANCHO=172
    -DPANTALLA_ALTO=320
