; ============================================================
; Tamagotchi Argentino — PlatformIO config
; Hardware: ESP32-C6 + LCD IPS 1.47" (ST7789/GC9107, 172x320)
; ============================================================
[env:esp32-c6-devkitc-1]
platform  = espressif32
board     = esp32-c6-devkitc-1
framework = arduino

; Velocidad de subida — ajustar según puerto serie
monitor_speed = 115200

; LovyanGFX desde el repo oficial
lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16

; Flags de compilación
build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0
    ; Resolución de la pantalla (puertos en config_pantalla.h)
    -DPANTALLA_ANCHO=172
    -DPANTALLA_ALTO=320
